
version: "3.7"

services:
  db:
    restart: always
    container_name: pg_gomoku
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_gomoku
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=4
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    container_name: redis_gomoku
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    env_file:
      - .env

#  backend:
#    env_file:
#      - .env
#    build: to_server
#    container_name: backend_gomoku
#    ports:
#      - "8888:8888"
#    restart: always
#    volumes:
#      - ./app/:/shurl/app
#    links:
#      - db
#
#    environment:
#      POSTGRES_SERVICE_USER: ${POSTGRES_USER}
#      POSTGRES_SERVICE_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_SERVICE_HOST: db
#      POSTGRES_SERVICE_PORT: ${POSTGRES_PORT}
#
#      DEBUG: ${DEBUG}
#
#    command: bash -c "python start.py"
#    depends_on:
#      - db
#      - redis

#  nginx:
#    restart: always
#    build: ./nginx/
#    container_name: ngingx_gomoku
#    ports:
#      - "80:80"
#    volumes:
#      - ./gomoku_front/build:/usr/src/app/static/
#    links:
#      - backend:backend
#    depends_on:
#      - backend